In [1]:
import numpy as np

In [2]:
a  = np.random.randint(2,size = (4,4))

In [115]:
a

array([[1, 1, 0, 0],
       [0, 1, 0, 1],
       [1, 0, 0, 1],
       [0, 1, 0, 0]])

In [117]:
a[][1:n]

array([1, 0])

In [109]:
n=3
element_number = 0
for i in range(n):
    element_number +=i
    if (i-n)==0:
        break
horizontal = np.zeros(element_number)
horizontal[0:n-1]= a[0][1:n]
horizontal[n-1:n+1] = a[1][2:n]
horizontal

array([1., 1., 0.])

In [108]:
n=3
horizontal = np.zeros(element_number)
for i in range(n):
    horizontanl = np.array()

TypeError: array() missing required argument 'object' (pos 0)

In [24]:
5 +4+3+2+1


15

In [69]:
horizontal = np.zeros(element_number)
horizontal[-1]=1
horizontal

array([0., 0., 0., 0., 0., 1.])

In [71]:
horizontal[n-1:n-3]

array([], dtype=float64)

In [72]:
bin(0)

'0b0'

In [76]:
m = np.random.randint(2, size = (element_number))
m

array([0, 0, 1, 1, 0, 1])

In [74]:
m

array([[1, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 1],
       [1, 1, 0, 0]])

In [3]:
k = 6
binary = int(bin(k)[2:])

In [43]:
n= 4
k = 3
binary = int(bin(k)[2:])
horizontal_matrix = np.array([int(i) for i in str(binary)])
horizontal_matrix

array([1, 1])

In [42]:
a = np.zeros((n,n))
a[0][1:n]=horizontal_matrix[0:n-1]
a[1][2:n]= horizontal_matrix[2:n]
# a[3][3:n] = horizontal_matrix[2:n-1]
a

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [34]:
horizontal_matrix[2:3]

array([0])

In [45]:
63*34

2142